### ISSUE TITLE
Parent relation doesn't honor del-attribute claims

### ISSUE THREAD

**Issue by aboodman** [camlistore/camlistore#562] opened 2015-01-05 08:00 UTC
If you add a child to a permanode via either camliMember or camliPath:*, then del-attribute it, it will cease to show up in the permanode's description, but searches via the parent relation will still find it.

You can reproduce this by patching https://camlistore-review.googlesource.com/#/c/4318/ against bc5fd6ea9d1b3f3a93874225f18716643de33765, then following these steps:

1. Add a file to the UI.
2. Select the file and click "Create set with items" in the sidebar
3. In the resulting view, go to the permanode aspect - note the camliMember row for the file
4. Go to the contents aspect, select the file, then click "Remove from set" in the sidebar
5. Note that the item is still in the content aspect
6. Go back to permanode aspect and note that camliMember row is gone

The permanode aspect is reading from the description of the permanode. The contents aspect is using a search with the 'parent' relation.

You can see the raw queries and responses in the network tab of Chrome's developer tools.

**Comment by mpl** [comment] 2015-01-05 17:35
Everytime I hear about del-attribute I have to think about why we can't get rid of it and do everything with delete claims instead, and it makes me sad to realize that we can't.
@bradfitz You want me to have a look at that or you got it?

**Comment by aboodman** [comment] 2015-01-05 17:50
For the uninitiated, can you remind why we can't use the delete claim instead?

Also, for this use case should I be using the delete claim?

**Comment by mpl** [comment] 2015-01-05 17:57
I think you actually could achieve the same thing with a delete claim. But it would be more work since you'd first have to find the original claim that set the attribute you want to undo (so that you can delete said claim).
Also, if we ever get to doing claims that set multiple things atomically, then there would be cases where we can't achieve a del-attribute with a delete claim without deleting other attributes in the operation, which we certainly don't want.
And there's probably another reason that I forget.

**Comment by aboodman** [comment] 2015-01-05 18:11
I see. It seems like atomic updates could be implemented by actually generating n claims, and linking them together, like, roughly:

{
  camliType: 'claim',
  permanode: 'xyz',
  attr: 'foo',
  value: 'bar',
  inGroup; true,
}

{
  camliType: 'claim-group',
  claims: ['abc', 'def', 'ghi'],  // blob refs of grouped claims
}

This way a group of changes can still be created (and later, deleted) individually ... but the indexer and other parties will know when they see it that it was meant to be part of a group, and can ignore until they see and validate the group.

**Comment by bradfitz** [comment] 2015-01-05 18:14
That is #110 ... see comment 4 there.

**Comment by aboodman** [comment] 2015-01-05 18:17
Oh, that's better. So out of curiosity, is there still need for del-attribute, apart from backward compat and the convenience issue that mathieu pointed out?

**Comment by aboodman** [comment] 2015-01-05 18:20
Answering own question: Yes, because you could end up needing to unwind a long chain of set/add-attributes which would be error prone and expensive.

**Comment by edrex** [comment] 2016-05-10 19:37
I can't reproduce the original issue. I think maybe it was a caching issue, somewhere, that is better now. I tested with both camliPath:* and camliMember attrs, by deleting them from the "Permanode" aspect and then switching to the "Contents" aspect and seeing that they are gone. Closing.

**Closed by edrex** 2016-05-10 19:37 UTC
Labels: Search
