### ISSUE TITLE
cmd/camput: silent error output when upload file

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#955] opened 2017-09-17 21:46 UTC
I have a long-running camput process running already, and try to do another camput.

Ideally parallel camput would work, but that's not what this bug is about.

Instead, this bug is about that `camput permanode` shows the real error output (the "have cache" is locked), but `camput file` just fails silently with no output (but exit status 1 at least).

```
brad5k:~ $ camput permanode
2017/09/17 14:44:45 Could not create/open new have cache at /Users/bradfitz/Library/Caches/Camlistore/camput.havecache.d30526d367b8aedab5e485d382916d7c9371f83d.leveldb, resource temporarily unavailable
brad5k:~ $ echo foo > bar
brad5k:~ $ camput file bar
brad5k:~ $ echo $?
1
```

**Comment by mpl** [comment] 2017-09-18 18:29
duplicate of #862  or #685 ?

**Comment by mpl** [comment] 2017-11-10 18:31
probably fixed by https://camlistore-review.googlesource.com/c/camlistore/+/6256

**Closed by mpl** 2017-11-10 18:31 UTC
