### ISSUE TITLE
map aspect: high memory usage of camlistored

### ISSUE THREAD

**Issue by tdilo** [camlistore/camlistore#934] opened 2017-07-02 22:08 UTC
On my camlistore instance, leaving the map aspect open in the browser (at default zoom level) nicely populates the map with markers over time (... a whole lot of markers. Fun to watch.). While the map is being populated, memory usage of camlistored goes through the roof.

Usually, my instance with a LevelDB index consumes about 1.5 GB of resident memory. After two minutes of loading map markers, the process reaches 6 GB of resident memory usage. This keeps on growing until the map aspect is closed and no further search queries are issued. While loading, approximately one search query per second is issued. The last query had a limit of 13750 (items?) set.

Some stats for reference:
> Scanned prefix "imagesize": 113784 rows
> Scanned prefix "exifgps": 3608 rows

I am currently syncing blobs (in-process, not with camtool) and am not quite sure if that might make a difference.

**Comment by mpl** [comment] 2017-07-03 16:07
I had only tried with a few hundred images, and there's no noticeable memory increase afaict. I suppose I need to expand my dataset to a few thousands and retry to reproduce.

**Comment by tdilo** [comment] 2017-07-03 22:01
Note that I did not perform any search and just switched to the map aspect, so CL 10467 definitely helps in avoiding the extreme growth rates in memory consumption. The problem persists when performing a search with a large result set, like `is:image` - but is less severe when performing a more reasonable location query (country level).

Imposing a client-side limit on the amount of markers drawn would probably be useful, as the browser starts getting sluggish as well with so many active markers on the map.

**Comment by mpl** [comment] 2017-07-04 13:40
yes, but before imposing that sort of limit, I'd like to diagnose the problem better.

Unfortunately I haven't been able to reproduce it so far. It seems like my largest actual dataset is ~5000 images, but only ~1200 of them seem to be having some GPS exif tags. And it seems like this is not enough to observe what you're seeing. Even with is:image, the markers show up almost instantaneously, and I don't see any significant memory increase.

Hmm, I've just thought of something. Were you testing with a local, or remote, Camlistore instance?

**Comment by tdilo** [comment] 2017-07-04 17:40
With a remote instance (self-signed certificate).

**Comment by mpl** [comment] 2017-07-05 17:29
One (independent) suggestion of @bradfitz is to load only the "best" markers. As in, if you have 200 items in Seattle, but you're at the word level zoom, then only load 1 marker for one of the Seattle items, because they're indistinguishable at that zoom level anyway.

I'm not sure that would solve your problem since I haven't determined yet where the mem usage is spent, but it can't hurt as a feature anyway. So I'll try and do that as the next CL, and we'll see if that kills two birds with one stone.

**Comment by tdilo** [comment] 2017-07-05 21:17
I like that suggestion, as the map does get quite full in some places. I'm not sure what the metric for the best marker would be though - most recent might be fine. Only showing a single marker would require manual zooming to discover places where more markers are hidden, though.

Another, similar approach would be to use client-side clustering with something like https://github.com/Leaflet/Leaflet.markercluster (looks good at a first glance). This might not fix the memory usage problem but I will debug that myself eventually, if you have trouble reproducing the issue.

**Comment by mpl** [comment] 2017-07-06 12:41
yes, I don't think the criterion for "best" marker matters much. I would start with whichever one comes first in the search results.

jsyk, even though it's high on my priority list (after cutting the release), I won't have much time to work on this in the next 10 days (afk most of the time). So please feel free to start debugging your high memory usage as soon as you can.

**Comment by bradfitz** [comment] 2017-07-06 15:43
I also think there's a problem here.

I did:
* searched for `is:post` in the UI
* switched to the Map view
* saw the map without any markers
* waited
* waited
* watched the server logs
* saw this number increasing:

```
Jul 06 08:40:15 ante camlistored.run[5804]: 2017/07/06 08:40:15 Added/updated search subscription for tag "q1"
Jul 06 08:40:16 ante camlistored.run[5804]: 2017/07/06 08:40:16 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":15000}}`
Jul 06 08:40:16 ante camlistored.run[5804]: 2017/07/06 08:40:16 Added/updated search subscription for tag "q1"
 Jul 06 08:40:16 ante camlistored.run[5804]: 2017/07/06 08:40:16 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":15050}}`
Jul 06 08:40:16 ante camlistored.run[5804]: 2017/07/06 08:40:16 Added/updated search subscription for tag "q1"
Jul 06 08:40:17 ante camlistored.run[5804]: 2017/07/06 08:40:17 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":15100}}`
Jul 06 08:40:17 ante camlistored.run[5804]: 2017/07/06 08:40:17 Added/updated search subscription for tag "q1"
Jul 06 08:40:17 ante camlistored.run[5804]: 2017/07/06 08:40:17 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":15150}}`
Jul 06 08:40:17 ante camlistored.run[5804]: 2017/07/06 08:40:17 Added/updated search subscription for tag "q1"
Jul 06 08:40:18 ante camlistored.run[5804]: 2017/07/06 08:40:18 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":15200}}`
Jul 06 08:40:18 ante camlistored.run[5804]: 2017/07/06 08:40:18 Added/updated search subscription for tag "q1"
Jul 06 08:40:18 ante camlistored.run[5804]: 2017/07/06 08:40:18 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":15250}}`
Jul 06 08:40:18 ante camlistored.run[5804]: 2017/07/06 08:40:18 Added/updated search subscription for tag "q1"
Jul 06 08:40:19 ante camlistored.run[5804]: 2017/07/06 08:40:19 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":15300}}`
Jul 06 08:40:19 ante camlistored.run[5804]: 2017/07/06 08:40:19 Added/updated search subscription for tag "q1"
Jul 06 08:40:19 ante camlistored.run[5804]: 2017/07/06 08:40:19 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":15350}}`
```

It keeps increasing.

It's subscribing to more and more queries?

Why's it incrementing over time?

It should do exactly 1 round trip to the server and not be some iterative discovery of markers.

Client: "Hi, this is my viewport and search query, give me the best 1,000 markers that are the most distinct."
Server: "Here are 1,000 results spread around the world, not too clustered."

Then user zooms in, and the process repeats, getting the new best 1,000.

**Comment by bradfitz** [comment] 2017-07-06 15:44
It's still going, and up to 4GB of memory.

And the number is still increasing:

```
Jul 06 08:43:57 ante camlistored.run[5804]: 2017/07/06 08:43:57 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":28050}}`
Jul 06 08:43:57 ante camlistored.run[5804]: 2017/07/06 08:43:57 Added/updated search subscription for tag "q1"
Jul 06 08:43:57 ante camlistored.run[5804]: 2017/07/06 08:43:57 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":28100}}`
Jul 06 08:43:57 ante camlistored.run[5804]: 2017/07/06 08:43:57 Added/updated search subscription for tag "q1"
Jul 06 08:44:00 ante camlistored.run[5804]: 2017/07/06 08:44:00 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":28150}}`
Jul 06 08:44:00 ante camlistored.run[5804]: 2017/07/06 08:44:00 Added/updated search subscription for tag "q1"
Jul 06 08:44:02 ante camlistored.run[5804]: 2017/07/06 08:44:02 Got websocket message `{"tag":"q1","query":{"sort":"-created","expression":"is:post","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":28200}}`
```

**Comment by mpl** [comment] 2017-07-07 20:53
I understand a bit more of what's happening.
Part of it is I naively mimicked the way the search aspect uses the search session. Every time we scroll down and more results are needed, a search query is sent. And when that search query succeeds, a callback sends a signal. The search aspect (blob item container really) gets that signal, and displays the new results.
What I did is: in loadMarkers, get all the relevant nodes from the current search session results, draw these nodes as markers, and when the batch is exhausted, ask for more results (in the same way the search aspect does). Then, when we get the success signal from the search session, callback on loadMarkers.
So, forgetting the best markers limit story for a moment, if we wanted to load all the results from the search as markers (which is what I would like to achieve properly first), it should work. It might make the UI sluggish, but there is no reason it should make Camlistore consume as much memory.

But what I found out today is that:
1) the search session almost entirely relies on websocket if it's available, which I hadn't expected (and I admit I hadn't read as well as a code path).
2) when the search aspect requests new results, the search session creates a new query that does not take into account the already fetched results, i.e. I think it does not use a continuation token, and the around parameter is actually not hooked up properly either. It just redoes the same request as previously, but with an increased limit. So, as we scroll down, we simply request everytime all the results from zero, but a larger batch of them everytime.

So since I pretty much wired the same mechanism for the map aspect, it's the reason why you see the limit increase in the logs. I can't explain yet why it does not eventually "work" for you (i.e why it does not stop after a while when you've gotten all the results, and why it uses up so much memory on the server-side), but I think that at least the (websocket's) search session behaviour is wrong even for the search aspect. It should either use a continuation token, or an around parameter, and not request the results from the start, and not with a continually increasing batch of results.

**Comment by tdilo** [comment] 2017-07-07 21:46
I think it never stops because it is unable to reach the end in time. I have a lot of photos, many of which do not have a geolocation at all.

**Comment by mpl** [comment] 2017-07-10 23:44
I've started on a work-around. CL tomorrow with any luck.

**Comment by mpl** [comment] 2017-07-12 13:43
@tdilo hi. Could you please try https://camlistore-review.googlesource.com/c/10546 out, and let me know if at least that allows you to load all the markers (and optionnally/hopefully fix the mem usage problem), for 'is:image' or whatever similar large search?

No need to review for now, I'm not done with it. But it would help if I knew I was on the right track with that.

**Comment by tdilo** [comment] 2017-07-12 20:29
Good news: you are on the right track. With the CL applied, runaway memory usage is fixed and all markers load as far as I can tell (the browser settles down after a while. Nothing obvious is missing). Search results arrive more quickly as well.

Memory usage of camlistored only increased by 350 MB after doing the `is:image` search repeatedly, and went down by 300 MB again after a while - looks normal.

**Comment by mpl** [comment] 2017-07-12 20:56
Excellent, thanks!

**Comment by mpl** [comment] 2017-07-13 15:59
@tdilo not sure it's totally ready for review, but I'm probably out of time for this week, so feel free to start reviewing please.

**Comment by mpl** [comment] 2017-07-22 02:08
https://camlistore-review.googlesource.com/10626

**Comment by mpl** [comment] 2017-08-01 00:10
@tdilo I've merged https://camlistore-review.googlesource.com/c/10546 , which should automatically close that issue.
Feel free to reopen if that is not the case please.

I'm going to open additional issues for the more advanced related features.

**Closed** 2017-08-01 00:12 UTC
Labels: WebUI
