### ISSUE TITLE
Twitter importer: Links in UI don't resolve correctly

### ISSUE THREAD

**Issue by DanielHeath** [camlistore/camlistore#783] opened 2016-05-23 04:07 UTC
Steps to repro: 
1) Import a twitter account. 
2) From `/ui/` in firefox, click the icon for the twitter account (a link to `/ui/sha1-c8dc15fca027d583c87a9b90a1644a72bf66acb2?q= ` - the first icon if the importer has run recently and added new tweets). 
3) Click on the icon for a single tweet (a link to `/ui/sha1-fd7f1e706133890ad51c83158ff4906e4d45a385?p=sha1-c8dc15fca027d583c87a9b90a1644a72bf66acb2`.

Expected: I can see the tweet
Actual: "No results found".

**Comment by edrex** [comment] 2016-05-23 04:47
I can't reproduce on latest head. What version are you on (/status/)?

**Comment by DanielHeath** [comment] 2016-05-23 05:09
camlistored status

Versions

Camlistore: 2016-02-13-d16ac53
Go: linux/amd64 go1.5.2, cgo=true
djpeg: djpeg available

**Comment by edrex** [comment] 2016-05-23 05:22
Ah, I think I see what's going on. Tweets with attached images have camliPath:foo.jpg attrs, but they point to static files rather than permanodes https://github.com/camlistore/camlistore/issues/470, which confuses the UI . We can work around this in the UI but probably better to make a decision about whether camliPaths to files are valid first.

**Comment by edrex** [comment] 2016-05-23 05:38
Closing as duplicate since @mpl described the UI issue in https://github.com/camlistore/camlistore/issues/470#issuecomment-66575516. Thanks for the report!

**Comment by DanielHeath** [comment] 2016-05-23 05:38
Aha - it does indeed work for tweets without attached images.

**Closed by edrex** 2016-05-23 05:38 UTC
Labels: Usability, WebUI
