### ISSUE TITLE
camlistored: JSON serialization error

### ISSUE THREAD

**Issue by ctessum** [camlistore/camlistore#927] opened 2017-05-17 23:11 UTC
The error 

```
Bad request: JSON serialization error: json: unsupported value: NaN
```

shows up in the camlistored output log after running the command:
```
camput -verbose file --permanode --tag=backup,documents $HOME/Documents
```
The error message is accompanied by everything disappearing from the user interface. The Documents directory contains tens of GB of data so it is difficult to tell the specific file or files that are causing this problem. I can ```camput``` smaller subdirectories without an issue.

This problem occurs both in the master built from source (```fc041f7381ea5e201844511e6241d2c95730668f```) and the most recent binary release (```2017-05-05```).

Let me know if there's anything I can do to get more information about what's going wrong.

**Comment by mpl** [comment] 2017-05-18 21:21
@ctessum as I have indeed no idea what could cause this among your input files, could you please apply https://camlistore-review.googlesource.com/10187 and retry , so we can try to get more insight into what's going on?

**Comment by ctessum** [comment] 2017-05-19 03:34
@mpl: I tried adding that print statement, as well as a couple of additonal ones: 

``` go
	js, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		log.Printf("DEBUG: %#v", data)
		v := reflect.ValueOf(data).Elem()
		blobs := v.FieldByName("Blobs")
		for i := 0; i < blobs.Len(); i++ {
			fmt.Printf("Blob: %#v\n", blobs.Index(i))
		}
		m := v.FieldByName("Describe").Elem().FieldByName("Meta")
		shas := m.MapKeys()
		for _, sha := range shas {
			mm := m.MapIndex(sha)
			fmt.Printf("Describe meta %#v: %#v\n", sha, mm)
			fmt.Printf("Describe meta Request %#v\n", mm.Elem().FieldByName("Request"))
		}

		BadRequestError(rw, fmt.Sprintf("JSON serialization error: %v", err))
		return
	}
```

When I run the server with these print statements, they output 24 GB of log data before I killed the program. I have included the beginning of the output below. The part of the file that I can load into memory on my machine does not include an NaN value; I'm not sure how I would go about searching through the rest. Let me know if there's anything else you think I should try.


```
2017/05/18 20:21:06 Starting camlistored version 2017-05-18-749d51281d+; Go go1.8 (linux/amd64)
2017/05/18 20:21:06 Starting to listen on http://localhost:3179
2017/05/18 20:21:06 ui: serving Closure from embedded resources
2017/05/18 20:21:06 Slurping corpus to memory from index...
2017/05/18 20:21:06 Slurping corpus to memory from index... (1/9: meta rows)
2017/05/18 20:21:06 Scanned prefix "meta": 242519 rows, 369.972282ms
2017/05/18 20:21:06 Slurping corpus to memory from index... (2/9: prefix "signerkeyid")
2017/05/18 20:21:06 Slurping corpus to memory from index... (3/9: prefix "claim")
2017/05/18 20:21:06 Slurping corpus to memory from index... (4/9: prefix "fileinfo")
2017/05/18 20:21:06 Slurping corpus to memory from index... (5/9: prefix "filetimes")
2017/05/18 20:21:06 Slurping corpus to memory from index... (6/9: prefix "imagesize")
2017/05/18 20:21:06 Slurping corpus to memory from index... (7/9: prefix "wholetofile")
2017/05/18 20:21:06 Slurping corpus to memory from index... (8/9: prefix "exifgps")
2017/05/18 20:21:06 Slurping corpus to memory from index... (9/9: prefix "mediatag")
2017/05/18 20:21:06 Scanned prefix "mediatag": 2 rows, 200.609µs
2017/05/18 20:21:06 Scanned prefix "imagesize": 6159 rows, 6.939021ms
2017/05/18 20:21:06 Scanned prefix "filetimes": 25318 rows, 65.674581ms
2017/05/18 20:21:06 Scanned prefix "wholetofile": 25318 rows, 94.991088ms
2017/05/18 20:21:06 Scanned prefix "signerkeyid": 1 rows, 95.031441ms
2017/05/18 20:21:06 Scanned prefix "fileinfo": 29520 rows, 183.506603ms
2017/05/18 20:21:06 Scanned prefix "claim": 7 rows, 183.516228ms
2017/05/18 20:21:06 Scanned prefix "exifgps": 72 rows, 183.663888ms
2017/05/18 20:21:06 Corpus stats: 63.578 MiB mem: 242519 blobs (13.738 GiB) (68773 schema (3 permanode, 29520 file (6159 image), ...)
2017/05/18 20:21:06 Corpus scanning CPU usage: 180ms
2017/05/18 20:21:07 [SyncHandler /bs/ -> /index/] Added 0 pending blobs from sync queue to pending list
2017/05/18 20:21:07 Available on http://localhost:3179/ui/
2017/05/18 20:21:09 DEBUG: &search.SearchResult{Blobs:[]*search.SearchResultBlob{(*search.SearchResultBlob)(0xc420b2e780), (*search.SearchResultBlob)(0xc420b2e790), (*sea
rch.SearchResultBlob)(0xc420b2e7b0)}, Describe:(*search.DescribeResponse)(0xc425dccc78), Continue:""}
Blob: &search.SearchResultBlob{Blob:blob.Ref{digest:blob.sha1Digest{0x32, 0x4a, 0xc6, 0x8e, 0xd, 0xe9, 0x13, 0x8e, 0x7, 0xb9, 0xde, 0x75, 0xba, 0x58, 0x5e, 0xa3, 0xd9, 0x
9a, 0x92, 0x18}}}
Blob: &search.SearchResultBlob{Blob:blob.Ref{digest:blob.sha1Digest{0xb1, 0x32, 0x0, 0x5c, 0x8d, 0x5, 0x2c, 0x20, 0xdd, 0x8c, 0xb, 0x30, 0xdb, 0x78, 0xd3, 0xcc, 0x4, 0x3e
, 0xa7, 0x3}}}
Blob: &search.SearchResultBlob{Blob:blob.Ref{digest:blob.sha1Digest{0x57, 0xc1, 0x7a, 0x3f, 0xeb, 0x43, 0x43, 0x6c, 0x6f, 0xfe, 0x95, 0x9d, 0x8a, 0x28, 0xdb, 0xfe, 0x65, 
0x13, 0x2e, 0x48}}}
Describe meta "sha1-ce5cfb837392f54b927d5c73001416fa71cbfae1": &search.DescribedBlob{Request:(*search.DescribeRequest)(0xc425bad740), BlobRef:blob.Ref{digest:blob.sha1Dig
est{0xce, 0x5c, 0xfb, 0x83, 0x73, 0x92, 0xf5, 0x4b, 0x92, 0x7d, 0x5c, 0x73, 0x0, 0x14, 0x16, 0xfa, 0x71, 0xcb, 0xfa, 0xe1}}, CamliType:"file", Size:991, Permanode:(*searc
h.DescribedPermanode)(nil), File:(*camtypes.FileInfo)(0xc42658e050), Dir:(*camtypes.FileInfo)(nil), Image:(*camtypes.ImageInfo)(0xc42071ffe8), MediaTags:map[string]string
(nil), DirChildren:[]blob.Ref(nil), Location:(*camtypes.Location)(nil), Stub:false}
Describe meta Request &search.DescribeRequest{BlobRefs:[]blob.Ref{blob.Ref{digest:blob.sha1Digest{0x32, 0x4a, 0xc6, 0x8e, 0xd, 0xe9, 0x13, 0x8e, 0x7, 0xb9, 0xde, 0x75, 0x
ba, 0x58, 0x5e, 0xa3, 0xd9, 0x9a, 0x92, 0x18}}, blob.Ref{digest:blob.sha1Digest{0xb1, 0x32, 0x0, 0x5c, 0x8d, 0x5, 0x2c, 0x20, 0xdd, 0x8c, 0xb, 0x30, 0xdb, 0x78, 0xd3, 0xc
c, 0x4, 0x3e, 0xa7, 0x3}}, blob.Ref{digest:blob.sha1Digest{0x57, 0xc1, 0x7a, 0x3f, 0xeb, 0x43, 0x43, 0x6c, 0x6f, 0xfe, 0x95, 0x9d, 0x8a, 0x28, 0xdb, 0xfe, 0x65, 0x13, 0x2
e, 0x48}}}, BlobRef:blob.Ref{digest:blob.digestType(nil)}, Depth:1, MaxDirChildren:0, At:types.Time3339{sec:0, nsec:0, loc:(*time.Location)(nil)}, Rules:[]*search.Describ
eRule{(*search.DescribeRule)(0xc420b12370), (*search.DescribeRule)(0xc420b123c0), (*search.DescribeRule)(0xc420b12410)}, sh:(*search.Handler)(0xc420775740), mu:sync.Mutex
{state:0, sema:0x0}, m:search.MetaMap{"sha1-6cd1bdf8713f8b35b3cf0358c8fabbc99b49bd10":(*search.DescribedBlob)(0xc425e72e80), "sha1-d7965c923f1ff9d178d193908c721ba77ae3b15
f":(*search.DescribedBlob)(0xc42851e200), "sha1-401d8f441576842d84b0191e0e551768016b28f6":(*search.DescribedBlob)(0xc428686300), "sha1-db9c603e637e5631ba5f00284a702f8ac2d
64fc0":(*search.DescribedBlob)(0xc4287f2180), "sha1-87704f9a170300dab406bf1fb9f8e24f36caee45":(*search.DescribedBlob)(0xc425daec00), "sha1-30f5ec415a37a42fed8f6d4e3e164a9
98378fbcd":(*search.DescribedBlob)(0xc425dfb600), "sha1-3fad190452bfd16152ade9f2b385aad934ec7c78":(*search.DescribedBlob)(0xc428693b00), "sha1-b8f3e70e595f6af250702ecac23
a2c956c38c34d":(*search.DescribedBlob)(0xc42883cd00), "sha1-6011de5702f7e36152cc1b95cacb71046a26eedd":(*search.DescribedBlob)(0xc42856c900), "sha1-00b4ccfe0f6967f6482ff81
90fe10429804d9707":(*search.DescribedBlob)(0xc4281abb80), "sha1-002f9d7a6d2f1e77c80eb3fd1b98a0d43dd9e700":(*search.DescribedBlob)(0xc428488280), "sha1-f2e5e2be8d311a53336
bf96ffca7393c6cf1c02f":(*search.DescribedBlob)(0xc428808580), "sha1-fccf6361b5b7b7fa7cdc9ae745b77f82a165de01":(*search.DescribedBlob)(0xc427006180), "sha1-1ea1f11bae224a2
0b8fcf33756f61516c7eb2790":(*search.DescribedBlob)(0xc425c9a280), "sha1-11f37beb54c0aecd75ae48d3645f25c0c87d6de7":(*search.DescribedBlob)(0xc4285e3000), "sha1-83012536b57
f5216636b323c10edfb33940dec7c":(*search.DescribedBlob)(0xc42860d300), "sha1-c74d47a4c97434de2a1d5f7ae9b801150e6bfe8d":(*search.DescribedBlob)(0xc42838cb80), "sha1-343bb28
701868a0795f144157409e060fad89bda":(*search.DescribedBlob)(0xc42844d400), "sha1-79eb7b3d0c3c0445b52d54c1759f2b23244301c2":(*search.DescribedBlob)(0xc4285d4280), "sha1-c61
aaf4d1425f3b215a82905fb7d96de4b43ea48":(*search.DescribedBlob)(0xc4283a2c00), "sha1-910373e7f18ded072edce5768aa33899a4f7de49":(*search.DescribedBlob)(0xc425c9a000), "sha1
-bce8d90fd4a3ea627f80a60726be3722754a1252":(*search.DescribedBlob)(0xc425e25680), "sha1-a95bb9b58350585218945fe951e97c0137b09c90":(*search.DescribedBlob)(0xc426e50100), "
sha1-f37a07bb5f13d8f8e908766844ad39aa7e43da72":(*search.DescribedBlob)(0xc425dafd00), "sha1-b0f69363e40d763da3cd54930daa20c4f88962f2":(*search.DescribedBlob)(0xc4285e3f80
), "sha1-73488cb44db4432050f7bc8e52bdff39e477987a":(*search.DescribedBlob)(0xc42859dd00), "sha1-5ec5058da0933719a05d0f1c1dd5b63ef8271fb4":(*search.DescribedBlob)(0xc42810
d700), "sha1-7a5dbf32d3937f521068b3183ca4c3eae2e3547c":(*search.DescribedBlob)(0xc428665f80), "sha1-5986067e701999d21bff3dd62919ed0c09cb5c10":(*search.DescribedBlob)(0xc4
26ee6500), "sha1-f1a9ab62765ec6b03ac6d8b8b43f0eac04a60c50":(*search.DescribedBlob)(0xc427414100), "sha1-f1d4ee6b6b4c49db88b78e04199edd913cb45838":(*search.DescribedBlob)(
0xc428612a80), "sha1-2f0c3e749883797577126c0c0d26270ef41fc510":(*search.DescribedBlob)(0xc4281ca780), "sha1-c4fe403a740917348a4a84b2b58426f0e86aea85":(*search.DescribedBl
ob)(0xc426408900), "sha1-9764e65a017958f1036bc352a6c4dd75b29b4547":(*search.DescribedBlob)(0xc4284f3f80), "sha1-1f2ff7a9a7bf909a7a1c17b786d2e83f14f355bc":(*search.Describ
edBlob)(0xc425ec0200), "sha1-c21963640655d405dc33a1d78f62f41a06efa722":(*search.DescribedBlob)(0xc428306780), "sha1-81af69c69c9e65807088e7f32f301066fc5d9c54":(*search.Des
cribedBlob)(0xc4281e0880), "sha1-b52380fb70a46a95d5786db26a4b7a32c7d1f7ad":(*search.DescribedBlob)(0xc428296b00), "sha1-1bee0263c3c4b19634627fa77b9dc84793384ace":(*search
.DescribedBlob)(0xc4284ce300), "sha1-0ccb16422800b08b60bf2de22d8848a3ea1772e6":(*search.DescribedBlob)(0xc420074d80), "sha1-fd7daec1eb874e1f0fa0e54ad587776ab414802a":(*se
```

**Comment by mpl** [comment] 2017-05-19 13:36
There are several things I don't understand about your answer:

1) Is the log growing that large simply because you're camputting a lot of things, or is it growing especially large because of the new debug prints?

2) If the latter, are you saying you're getting lots of json.MarshalIndent errors which are _not_ then NaN one you reported? I thought that NaN error was the only problem...

3) Why would you have to load the 24GB of logs in memory? Can't you redirect the log output to a file, and then grep that file for the NaN error message?

In any case, if we want to focus on the NaN error, you could 1) add a check to only output when it's the NaN error, 2) make it a fatal error so the program terminates and the error we care about would be at the end of the log. Something like:

https://camlistore-review.googlesource.com/c/10187/3/pkg/httputil/httputil.go

**Comment by ctessum** [comment] 2017-05-19 16:02
Sorry for being unclear. There is only one json.MarshalIndent error. The problem is that the data object that causes the error when it is marshalled is large (or has circular references), so it is difficult to see exactly where the NaN value is within the object. 

The output from the print statement you suggest is here:
```
2017/05/18 20:21:09 DEBUG: &search.SearchResult{Blobs:[]*search.SearchResultBlob{(*search.SearchResultBlob)(0xc420b2e780), (*search.SearchResultBlob)(0xc420b2e790), (*search.SearchResultBlob)(0xc420b2e7b0)}, Describe:(*search.DescribeResponse)(0xc425dccc78), Continue:""}
```

The rest of the 24GB of logs were the result of me trying to go through this ```search.SearchResult``` value and figure out exactly where the NaN value is. I did redirect the log output to a file, but I forgot about grep and I was trying to search using a text editor, which requires loading it into memory. I could continue working on this, but it also seems possible that there might be circular references that would continue printing forever.

**Comment by mpl** [comment] 2017-05-19 17:21
Ok, I think I have an idea on how to debug that. Stay tuned.

**Comment by mpl** [comment] 2017-05-19 20:21
my idea did not work out as I expected, but otoh, I remembered about using spew, which is probably a better idea, so could you please rerun with something like:

 https://camlistore-review.googlesource.com/c/10187/4/pkg/httputil/httputil.go

I'm pretty hopeful we'll see what field has a NaN with that kind of dump.

**Comment by ctessum** [comment] 2017-05-20 22:33
That worked. The NaN values are lat-lon coordinates:
``` go 

       gps: (map[blob.Ref]index.latLong) {
		...
        (blob.Ref) (PANIC=runtime error: invalid memory address or nil pointer dereference){
         digest: (blob.sha1Digest) {
          00000000  b1 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
          00000010  9a 51 9f cc                                       |.Q..|
         }
        }: (index.latLong) {
         lat: (float64) NaN,
         long: (float64) NaN
        },

```
It looks like it can be fixed by changing line 634 in pkg/index/receive.go to this:
``` go
		if math.Abs(long) > 180.0 || math.Abs(lat) > 90.0 || math.IsNaN(lat) || math.IsNaN(long) || math.IsInf(lat, 0) || math.IsInf(long, 0) {
```
When I make that change, recompile, and re-camput all the files the error goes away.

**Comment by mpl** [comment] 2017-05-21 00:39
yeah I was suspecting some coordinates when I saw from your corpus that you had some exifgps entries, but I first wanted to have a method for debugging that, for the next time something similar happens.

I feel like we already had a similar problem in the past so I want to dig a little in the history before making any change, especially since you now have a work-around in the meantime.

**Comment by ctessum** [comment] 2017-05-21 01:28
OK. Let me know if you need anything else from me.

**Comment by mpl** [comment] 2017-05-22 15:04
@ctessum ok, that's exactly the place where I remembered we added a fix for floats (rev 95f9a6b9a81408c7e5e6ae00e2425e9de0a4f0c1), only I guess none of us thought the new check did not cover Nan.

In general I agree with the proposed change, but maybe I'd check for NaN before checking for the bounds. Not sure what's the better optimization.

Also, I think we don't need the check for Inf, as it's redundant with the bounds check (even for negative inf, since we use math.Abs).

Finally, we need tests with that change. Something similar to what was done with 95f9a6b9a81408c7e5e6ae00e2425e9de0a4f0c1 would do. 

Do you want to propose a CL, or shall I do it?

**Comment by ctessum** [comment] 2017-05-22 16:49
Thanks, @mpl. If you're willing to make the changes, that's fine with me.

**Comment by mpl** [comment] 2017-05-22 19:52
ack, I'm on it.

**Comment by mpl** [comment] 2017-05-22 20:28
@ctessum btw, I'd be interested if you could identify which one of your images was causing the exif lib to spit out a NaN. It would make writing the test to reproduce that case easier.

**Comment by ctessum** [comment] 2017-05-23 02:10
I'm not quite familiar enough with the code to know how to go about doing that, but let me know if you have any ideas.

**Comment by mpl** [comment] 2017-05-23 14:29
@ctessum I was able to forge a failing EXIF, so I don't need to see yours anymore that much. But let me know if you're interested to flush yours out (for your own curiosity), and I'll try to figure it out.

Also, please feel free to review https://camlistore-review.googlesource.com/10187

**Comment by ctessum** [comment] 2017-05-23 16:02
I'm not sure how to use gerritt, but the changes look good to me except that I haven't previously seen the practice of taking the absolute value before checking for NaN: ``` math.IsNaN(math.Abs(lat))```. Is there a reason to do that?

**Comment by mpl** [comment] 2017-05-23 20:38
Nope, that was just me being distracted, thanks!
Fixed, and merged.

**Closed** 2017-05-23 21:04 UTC
