### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#533] opened 2014-10-21 10:03 UTC
<pre>The Camlistore web UI assumes the user has a low-latency connection or has a browser
with SPDY or HTTP/2 enabled. (we have lots of tiny js and css files, not merged
together, by choice)

Currently browsers don't have HTTP/2 support enabled by default, and Go's HTTP/2 support
(<a href="https://github.com/bradfitz/http2)">https://github.com/bradfitz/http2)</a> isn't quite done.

Tagging for 0.9 but this will likely slip.</pre>

**Comment by bradfitz** [comment] 2015-01-09 16:42
@mpl update third_party to latest version...

**Comment by mpl** [comment] 2015-01-13 00:52
https://camlistore-review.googlesource.com/4346

**Comment by mpl** [comment] 2015-01-13 16:38
a27306d74ae43f8f869339c5c7513707c9d350dc merged

**Comment by mpl** [comment] 2015-01-22 14:37
with 5f041a3b6af5d4b73906c633691187595cad99c5 in, fixing the problems caused by SNI, I think we're good now.

**Closed by mpl** 2015-01-22 14:37 UTC
Labels: accepted, priority-low
