### ISSUE TITLE
doc: strip .md suffix from doc URLs

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#742] opened 2016-04-29 17:10 UTC
It seems like exposing the .md extension in URLs like https://camlistore.org/doc/schema/permanode.md couples published docs to md unnecessarily. @willnorris what do you think?

Also, I don't want to call it out on the ML if you're not ready to announce yet, but fantastic work on the docs this week! I had to focus on other things this week, but I'm looking forward digging in and working on docs now that they've been cleaned up and reorganized. Thanks so much!

**Comment by edrex** [comment] 2016-04-29 17:14
Actually we just need to update the links, as https://camlistore.org/doc/schema/permanode works

**Comment by willnorris** [comment] 2016-04-29 17:51
closing as duplicate of #732 (Brad fixed the first half of that bug; .md extension is the second half)

**Closed by willnorris** 2016-04-29 17:51 UTC

**Comment by willnorris** [comment] 2016-04-29 17:53
and by the way, we can't just update the links because then that would break browsing the docs on GitHub (e.g. https://github.com/camlistore/camlistore/tree/master/doc/schema).  The links have to have the .md extension, which we'll then strip either on the client with some js and/or on the server side with a redirect to the canonical URL.

**Comment by edrex** [comment] 2016-04-29 18:07
ah makes sense
