### ISSUE TITLE
FUSE mount - at command doesn't properly walk subdirectories

### ISSUE THREAD

**Issue by bdillahu** [camlistore/camlistore#826] opened 2016-07-21 01:46 UTC
As nearly as I can tell, using the "at" directory in the FUSE mount should allow you to go "back in time" to the condition at that time (correct?). Seems to work fine for individual permanodes/files, but I've found an instance that doesn't seem to work.

(Please excuse if this is long winded... trying to make sure I explain this well)

If you create a tree of directories, and then rearrange it, and go "back in time" to the point where it should be before it was rearranged, you don't get all the changes reverted, just the top level.

Here's an example... hope this makes sense.

> ~/test_mount/roots > cd Tree_Root 
> ~/test_mount/roots/Tree_Root > ls
> ~/test_mount/roots/Tree_Root > mkdir root1
> ~/test_mount/roots/Tree_Root > mkdir root2
> ~/test_mount/roots/Tree_Root > mkdir root1/subroot1.1
> ~/test_mount/roots/Tree_Root > mkdir root1/subroot1.2 
> ~/test_mount/roots/Tree_Root > mkdir root2/subroot2.1
> ~/test_mount/roots/Tree_Root > mkdir root2/subroot2.2 
> ~/test_mount/roots/Tree_Root > cd ..

Here's what it looks like:

> ~/test_mount/roots > tree Tree_Root 
Tree_Root
├── root1
│   ├── subroot1.1
│   └── subroot1.2
└── root2
    ├── subroot2.1
    └── subroot2.2

6 directories, 0 files

Permanode time on "Tree_Root" was for the last claim (creating root2) was:

2016-07-21T01:07:12.952624569Z

So: 

> ~/test_mount/at/2016-07-21T01:07:13Z > tree
└── Tree_Root
    ├── root1
    │   ├── subroot1.1
    │   └── subroot1.2
    └── root2
        ├── subroot2.1
        └── subroot2.2

Now I wait a little while (to make the time easy to deal with) and rearrange things (note the new root3):

> ~/test_mount/roots > tree Tree_Root 
Tree_Root
└── root3
    ├── root1
    │   └── subroot1.2
    └── root2
        ├── subroot1.1
        ├── subroot2.1
        └── subroot2.2

Permanode time on "Tree_Root" for last claim is now:

2016-07-21T01:17:03.208325956Z

So:

> ~/test_mount/at/2016-07-21T01:17:03.208325956Z > tree Tree_Root 
Tree_Root
└── root3
    ├── root1
    │   └── subroot1.2
    └── root2
        ├── subroot1.1
        ├── subroot2.1
        └── subroot2.2

Now for the problem - look at the old time again:

> ~/test_mount/at/2016-07-21T01:07:13Z > tree Tree_Root  
Tree_Root
├── root1
│   └── subroot1.2
└── root2
    ├── subroot1.1
    ├── subroot2.1
    └── subroot2.2

6 directories, 0 files

Note that root1 and root2 are correct (and root3 is gone, also correct), but not that subroot1.1 is in the wrong place. It appears that we aren't getting the "old" version of root2 - the time isn't being passed down.

Please let me know if I'm just misunderstanding something.

Thanks!

**Comment by bdillahu** [comment] 2016-07-26 18:10
OK, as a follow-on... I can recreate this in Linux, but it seems to work correctly/as expected in Mac OS X.

**Comment by bdillahu** [comment] 2016-07-26 19:22
And logs:

From linux (note the various Sending request At 0001-01-01 00:00:00 +0000 UTC):

2016/07/26 15:18:03 fs.atDir: Lookup("2016-07-26T15:08")
2016/07/26 15:18:03 fs.atDir: Lookup("2016-07-26T15:08")
2016/07/26 15:18:05 fs.atDir: Lookup("2016-07-26T15:17")
2016/07/26 15:18:05 fs.atDir: Lookup("2016-07-26T15:17")
2016/07/26 15:18:06 fs.roots: querying
2016/07/26 15:18:06 fs.roots: querying
2016/07/26 15:18:06 rootsDir.ReadDirAll() -> [{0 unknown Tree_Root}]
2016/07/26 15:18:06 fs.roots: Lookup("Tree_Root")
2016/07/26 15:18:06 roDir.populate("Tree_Root") - Sending request At 2016-07-26 15:17:00 +0000 UTC
2016/07/26 15:18:06 roDir("Tree_Root") appending inode 406ea227ce9360ba, {Inode:4642826557718749370 Type:unknown Name:root3}
2016/07/26 15:18:06 roDir("Tree_Root").Lookup("root3") = &fs.roDir{fs:(*fs.CamliFileSystem)(0xc8200169b0), permanode:blob.Ref{digest:blob.sha1Digest{0x40, 0x6e, 0xa2, 0x27, 0xce, 0x93, 0x60, 0xba, 0xec, 0x4b, 0xff, 0x4d, 0x1, 0xe0, 0x12, 0xf0, 0x5a, 0xae, 0xf2, 0x48}}, parent:(*fs.roDir)(0xc8201be6c0), name:"root3", at:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, mu:sync.Mutex{state:0, sema:0x0}, children:map[string]fs.roFileOrDir(nil), xattrs:map[string][]uint8{}}, <nil>
2016/07/26 15:18:06 roDir.populate("Tree_Root/root3") - Sending request At 0001-01-01 00:00:00 +0000 UTC
2016/07/26 15:18:06 roDir("Tree_Root/root3") appending inode 81d1787cad8945b2, {Inode:9354390377907963314 Type:unknown Name:root1}
2016/07/26 15:18:06 roDir("Tree_Root/root3") appending inode 6568a5474f8474af, {Inode:7307272121103971503 Type:unknown Name:root2}
2016/07/26 15:18:06 roDir("Tree_Root/root3").Lookup("root1") = &fs.roDir{fs:(*fs.CamliFileSystem)(0xc8200169b0), permanode:blob.Ref{digest:blob.sha1Digest{0x81, 0xd1, 0x78, 0x7c, 0xad, 0x89, 0x45, 0xb2, 0x2e, 0xc9, 0xac, 0x1a, 0xaa, 0x74, 0xc9, 0xad, 0x62, 0xd3, 0x4c, 0xf5}}, parent:(*fs.roDir)(0xc820496240), name:"root1", at:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, mu:sync.Mutex{state:0, sema:0x0}, children:map[string]fs.roFileOrDir(nil), xattrs:map[string][]uint8{}}, <nil>
2016/07/26 15:18:06 roDir("Tree_Root/root3").Lookup("root2") = &fs.roDir{fs:(*fs.CamliFileSystem)(0xc8200169b0), permanode:blob.Ref{digest:blob.sha1Digest{0x65, 0x68, 0xa5, 0x47, 0x4f, 0x84, 0x74, 0xaf, 0xfa, 0x7d, 0x70, 0x34, 0x58, 0x4b, 0x2e, 0xf4, 0xe8, 0xf, 0x59, 0xaa}}, parent:(*fs.roDir)(0xc820496240), name:"root2", at:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, mu:sync.Mutex{state:0, sema:0x0}, children:map[string]fs.roFileOrDir(nil), xattrs:map[string][]uint8{}}, <nil>
2016/07/26 15:18:06 roDir.populate("Tree_Root/root3/root1") - Sending request At 0001-01-01 00:00:00 +0000 UTC
2016/07/26 15:18:06 roDir("Tree_Root/root3/root1") appending inode 6d32e664be9a2177, {Inode:7868604819338568055 Type:unknown Name:subroot1.2}
2016/07/26 15:18:06 roDir("Tree_Root/root3/root1").Lookup("subroot1.2") = &fs.roDir{fs:(*fs.CamliFileSystem)(0xc8200169b0), permanode:blob.Ref{digest:blob.sha1Digest{0x6d, 0x32, 0xe6, 0x64, 0xbe, 0x9a, 0x21, 0x77, 0xca, 0x22, 0x48, 0xe9, 0x1d, 0x2, 0x4c, 0xc0, 0x7a, 0x8a, 0x51, 0x8e}}, parent:(*fs.roDir)(0xc8204968a0), name:"subroot1.2", at:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, mu:sync.Mutex{state:0, sema:0x0}, children:map[string]fs.roFileOrDir(nil), xattrs:map[string][]uint8{}}, <nil>
2016/07/26 15:18:06 roDir.populate("Tree_Root/root3/root1/subroot1.2") - Sending request At 0001-01-01 00:00:00 +0000 UTC
2016/07/26 15:18:06 roDir.populate("Tree_Root/root3/root2") - Sending request At 0001-01-01 00:00:00 +0000 UTC
2016/07/26 15:18:06 roDir("Tree_Root/root3/root2") appending inode 8cbe5c487fadcbe8, {Inode:10141644877334432744 Type:unknown Name:subroot2.2}
2016/07/26 15:18:06 roDir("Tree_Root/root3/root2") appending inode b45b23d32dada4b1, {Inode:12996020539619124401 Type:unknown Name:subroot1.1}
2016/07/26 15:18:06 roDir("Tree_Root/root3/root2") appending inode 2f14fc608983643b, {Inode:3392613910870975547 Type:unknown Name:subroot2.1}
2016/07/26 15:18:06 roDir("Tree_Root/root3/root2").Lookup("subroot2.2") = &fs.roDir{fs:(*fs.CamliFileSystem)(0xc8200169b0), permanode:blob.Ref{digest:blob.sha1Digest{0x8c, 0xbe, 0x5c, 0x48, 0x7f, 0xad, 0xcb, 0xe8, 0xdd, 0x44, 0x6e, 0xd7, 0xcb, 0xfa, 0x4d, 0xa, 0xfd, 0xae, 0x16, 0x39}}, parent:(*fs.roDir)(0xc820496900), name:"subroot2.2", at:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, mu:sync.Mutex{state:0, sema:0x0}, children:map[string]fs.roFileOrDir(nil), xattrs:map[string][]uint8{}}, <nil>
2016/07/26 15:18:06 roDir("Tree_Root/root3/root2").Lookup("subroot1.1") = &fs.roDir{fs:(*fs.CamliFileSystem)(0xc8200169b0), permanode:blob.Ref{digest:blob.sha1Digest{0xb4, 0x5b, 0x23, 0xd3, 0x2d, 0xad, 0xa4, 0xb1, 0xc2, 0xe0, 0x82, 0x74, 0xe9, 0x19, 0x46, 0x1a, 0xe3, 0x3, 0x7c, 0x78}}, parent:(*fs.roDir)(0xc820496900), name:"subroot1.1", at:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, mu:sync.Mutex{state:0, sema:0x0}, children:map[string]fs.roFileOrDir(nil), xattrs:map[string][]uint8{}}, <nil>
2016/07/26 15:18:06 roDir("Tree_Root/root3/root2").Lookup("subroot2.1") = &fs.roDir{fs:(*fs.CamliFileSystem)(0xc8200169b0), permanode:blob.Ref{digest:blob.sha1Digest{0x2f, 0x14, 0xfc, 0x60, 0x89, 0x83, 0x64, 0x3b, 0xde, 0x91, 0x24, 0xae, 0x30, 0xe6, 0x42, 0xb7, 0xb7, 0x99, 0xb8, 0xc6}}, parent:(*fs.roDir)(0xc820496900), name:"subroot2.1", at:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, mu:sync.Mutex{state:0, sema:0x0}, children:map[string]fs.roFileOrDir(nil), xattrs:map[string][]uint8{}}, <nil>
2016/07/26 15:18:06 roDir.populate("Tree_Root/root3/root2/subroot1.1") - Sending request At 0001-01-01 00:00:00 +0000 UTC
2016/07/26 15:18:06 roDir.populate("Tree_Root/root3/root2/subroot2.1") - Sending request At 0001-01-01 00:00:00 +0000 UTC
2016/07/26 15:18:06 roDir.populate("Tree_Root/root3/root2/subroot2.2") - Sending request At 0001-01-01 00:00:00 +0000 UTC
2016/07/26 15:18:06 root.Lookup(at)
2016/07/26 15:18:06 fs.atDir: Lookup(".git")
2016/07/26 15:18:06 Can't parse time: unparsable timestamp
2016/07/26 15:18:06 fs.atDir: Lookup(".hg")
2016/07/26 15:18:06 Can't parse time: unparsable timestamp
2016/07/26 15:18:06 fs.atDir: Lookup(".bzr")
2016/07/26 15:18:06 Can't parse time: unparsable timestamp
2016/07/26 15:18:06 root.Lookup(.git)
2016/07/26 15:18:06 Bogus root lookup of ".git"
2016/07/26 15:18:06 root.Lookup(.hg)
2016/07/26 15:18:06 Bogus root lookup of ".hg"
2016/07/26 15:18:06 root.Lookup(.bzr)
2016/07/26 15:18:06 Bogus root lookup of ".bzr"

from Mac OS X:

2016/07/26 15:17:44 rootsDir.ReadDirAll() -> [{0 unknown Tree_Root}]
2016/07/26 15:17:44 roDir("Tree_Root") appending inode 80e846f8a72ce641, {Inode:9288752265222219329 Type:unknown Name:root3}
2016/07/26 15:17:44 roDir("Tree_Root/root3") appending inode 44e7fba37bf586b3, {Inode:4965213793777190579 Type:unknown Name:root1}
2016/07/26 15:17:44 roDir("Tree_Root/root3") appending inode 99409e7ae552c006, {Inode:11043000536983060486 Type:unknown Name:root2}
2016/07/26 15:17:44 roDir("Tree_Root/root3/root1") appending inode a400539d4dfeb3e6, {Inode:11817537357303690214 Type:unknown Name:subroot1.2}
2016/07/26 15:17:44 roDir("Tree_Root/root3/root2") appending inode 214d8b22da64efb0, {Inode:2399727158267539376 Type:unknown Name:subroot1.1}
2016/07/26 15:17:44 roDir("Tree_Root/root3/root2") appending inode 439e35b51623de99, {Inode:4872390898738257561 Type:unknown Name:subroot2.1}
2016/07/26 15:17:44 roDir("Tree_Root/root3/root2") appending inode 7492be6e07094f71, {Inode:8399985634773127025 Type:unknown Name:subroot2.2}
2016/07/26 15:17:44 fs.atDir: Lookup(".git")
2016/07/26 15:17:44 Can't parse time: unparsable timestamp
2016/07/26 15:17:44 fs.atDir: Lookup(".hg")
2016/07/26 15:17:44 Can't parse time: unparsable timestamp
2016/07/26 15:17:44 fs.atDir: Lookup(".bzr")
2016/07/26 15:17:44 Can't parse time: unparsable timestamp
2016/07/26 15:17:44 root.Lookup(.git)
2016/07/26 15:17:44 Bogus root lookup of ".git"
2016/07/26 15:17:44 root.Lookup(.hg)
2016/07/26 15:17:44 Bogus root lookup of ".hg"
2016/07/26 15:17:44 root.Lookup(.bzr)
2016/07/26 15:17:44 Bogus root lookup of ".bzr"


I'm really leaning toward this being an issue with RO/xattr stuff in roots.go - it looks like (to me) that if something is deemed RO, then the xattr is passed and not the time stamp... but not sure.

And I don't understand the Mac OS X vs Linux difference, unless one supports something that the other doesn't.

**Comment by mpl** [comment] 2016-07-26 23:00
thanks, I'll try and reproduce.

as for the linux VS macos difference, their FUSE implementation is completely different, so it could be anything in there.

**Comment by mpl** [comment] 2016-07-26 23:28
Right, I think can reproduce something similar. that's fun. I'll look into it.

**Comment by mpl** [comment] 2016-07-28 17:30
@bdillahu so I can reproduce the kind of inconsistency you're seeing but only at the root level for now, and it should be fixed by
https://camlistore-review.googlesource.com/6966

Maybe what you're seeing at deeper levels is the result of the roots dir bug but I'm not sure for now. In any case, can you try the above CL and let me know if that fixes the problem (partially or not) for you please?

**Comment by bdillahu** [comment] 2016-07-28 20:03
@mpl Sorry, that doesn't seem to change anything for me... 

Still seems OK on Mac, broken on Linux

**Comment by mpl** [comment] 2016-07-28 20:09
@bdillahu just to be sure, since you're new here: you've applied the CL I linked, and rebuilt everything (camlistored, and cammount) with it, right?

**Comment by bdillahu** [comment] 2016-07-28 20:16
@mpl Yep, near as I can tell, I did it right (you're right to question... I'm new at the go and Gerrit world).

I used the 

git fetch https://camlistore.googlesource.com/camlistore refs/changes/66/6966/1 && git checkout FETCH_HEAD

command from the CL, checked it onto a new branch in my git tree, and then did a

> go run make.go 

At the root level (and I double checked that the executables had a new date/time).

I won't swear to anything, but I think I did it right :-)

**Comment by mpl** [comment] 2016-07-28 21:09
@bdillahu I still need to find a stable repro so I can make sure to fix it, so I'm sorry to push changes blindly for now, but can your retry again (patchset 2) please?

**Comment by bdillahu** [comment] 2016-07-29 00:41
@mpl Yeah!

I think you got it... worked on Linux and Mac both.

Now I will say, on the test you created, I'm not 100% sure the code covers the sub directory level issue I started out with. Since the bottom level of the test directories are both named "1", I'm not sure if it didn't move around it would be caught.

But... I also don't fully grok that code, so I may be totally wrong.

You've fixed it, just not sure the test would catch if it failed again :-)

Thanks!

**Comment by bdillahu** [comment] 2016-07-29 02:09
Sorry, didn't see that :-)

**Comment by mpl** [comment] 2016-07-29 21:50
@bdillahu I'm not sure I understand your concern. I wrote that test because that was the first case I was able to find that seemed to reproduce a bug similar to yours.

what the test does is:

1) create roots/foo/1/1/1
2) create roots/foo/2/1
3) wait and record that time t1
4) mv roots/foo/1/1/1 roots/foo/2/1/1
4) wait and record that time t2

5) check that:
- roots/foo/at/t1/1/1/1 does exist
- roots/foo/at/t1/2/1/1 does not exist
- roots/foo/at/t2/1/1/1 does not exist
- roots/foo/at/t2/2/1/1 does exist

The test does fail before the CL is applied, and passes after.

If that does not seem satisfactory, can you please explain better?

**Comment by mpl** [comment] 2016-07-29 21:51
@edrex PTAL

**Comment by bdillahu** [comment] 2016-07-30 01:01
@mpl Yes, that seems fine... sorry, I got confused reading the code and missed one directory level, which threw off what I was thinking. I believe it's a valid test of what we were seeing (as you have confirmed also)...

(PTAL - had to look that one up - you guys have your own set of acronyms :-))

**Closed** 2016-08-01 16:48 UTC
